version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DB_USER=scim_user
      - DB_HOST=postgres
      - DB_NAME=scim_db
      - DB_PASSWORD=Pa55word
      - DB_PORT=5432
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=scim_user
      - POSTGRES_PASSWORD=Pa55word
      - POSTGRES_DB=scim_db
